services:
  caddy:
    container_name: caddy
    build:
      context: ./caddy
      args:
        - CADDY_CONFIG=Caddyfile.dev
    image: caddy
    networks:
      - dev
      - monitoring
    restart: unless-stopped
    ports:
      - "127.0.0.1:${PORT}:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    develop:
      watch:
        - path: ./caddy/Caddyfile.dev
          target: /etc/caddy/Caddyfile
          action: rebuild
          exec:
            command: ["caddy", "reload", "--config", "/etc/caddy/Caddyfile"]
    healthcheck:
      test: ["CMD", "caddy", "validate", "--config", "/etc/caddy/Caddyfile"]
      interval: 10s
      timeout: 10s
      retries: 3

  prometheus:
    container_name: prometheus
    image: prom/prometheus:main@sha256:cc486edb7d313138f1b2020057a9e0ad77cd2ab211a549a5d6bc67d4e062ab24
    networks:
      - monitoring
    restart: unless-stopped
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus/"
      - "--web.external-url=/prometheus/"
      - "--web.route-prefix=/"
    volumes:
      - ./services/monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
      - minio_jwt:/etc/prometheus/:ro  # minio_prometheus_jwt.txt written by minio-init
    depends_on:
      caddy:
        condition: service_started
      minio-init:
        condition: service_completed_successfully

  grafana:
      container_name: grafana
      image: grafana/grafana-oss:12.2.0-17142428006
      networks:
        - monitoring
      restart: unless-stopped
      volumes:
        - grafana_data:/var/lib/grafana
        - ./services/monitoring/grafana/provisioning:/etc/grafana/provisioning:ro
        - ./services/monitoring/grafana/dashboards:/etc/grafana/dashboards:ro
        - ./services/monitoring/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
      depends_on:
        prometheus:
          condition: service_started
      secrets:
        - grafana_admin_user
        - grafana_admin_pwd
      environment:
        - GF_SECURITY_ADMIN_USER__FILE=/run/secrets/grafana_admin_user
        - GF_SECURITY_ADMIN_PASSWORD__FILE=/run/secrets/grafana_admin_pwd
        - GF_SERVER_ROOT_URL=https://localhost:${PORT}/grafana/
        - GF_SERVER_SERVE_FROM_SUB_PATH=true

  postgres:
    container_name: postgres
    image: postgres:18.3-alpine3.23@sha256:4da1a4828be12604092fa55311276f08f9224a74a62dcb4708bd7439e2a03911
    networks:
      - dev
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./services/postgres/init:/docker-entrypoint-initdb.d:ro
    secrets:
      - postgres_db
      - postgres_user
      - postgres_pwd
    environment:
      - POSTGRES_DB_FILE=/run/secrets/postgres_db
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_pwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/postgres_user) -d $(cat /run/secrets/postgres_db)"]
      interval: 10s
      timeout: 5s
      retries: 3

  # https://images.chainguard.dev/directory/image/minio/overview
  # minio is not maintained anymore so I choose to go for the chainguard community maintenance
  minio:
    container_name: minio
    image: cgr.dev/chainguard/minio@sha256:29e9fe1fc994f5836d680f74ceae381b092f05ac4f9653a7a4d72289cd0ec5ab # found with docker inspect cgr.dev/chainguard/minio:latest --format='{{index .RepoDigests 0}}'
    networks:
      - dev
      - monitoring
    restart: unless-stopped
    volumes:
      - minio_data:/data
    secrets:
      - minio_admin_user
      - minio_admin_pwd # natively requires a minimum of 8 characters btw
    environment:
      MINIO_ROOT_USER_FILE: /run/secrets/minio_admin_user
      MINIO_ROOT_PASSWORD_FILE: /run/secrets/minio_admin_pwd
      MINIO_API_CORS_ALLOW_ORIGIN: "https://localhost:${PORT}" # we are not allowed to use mc cors set command without an entreprise image of minio, so there is no other way that allowing a specific origin for CORS
    ports: # temporary
      - "127.0.0.1:9000:9000" # to test metrics endpoint
      - "127.0.0.1:9001:9001" # CLI exposed for local debug
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: server /data --console-address :9001

  # This is an initializatioon container that is run after minio is healthy, it is used for:
  # - applying the CORS policy (required for browser presigned URL (PUT/GET))
  # - generates the Prometheus JWT and writes it to a shared volume between minio and prometheus
  # - creates a ft-box bucket (temporary test)
  minio-init:
    container_name: minio-init
    build:
      context: ./services/minio/init
    image: minio-init
    networks:
      - dev
    restart: "no"
    volumes:
      - minio_jwt:/jwt
    secrets:
      - minio_admin_user
      - minio_admin_pwd
    depends_on:
      minio:
        condition: service_healthy

volumes:
  caddy_data:
  caddy_config:
  prometheus_data:
  grafana_data:
  postgres_data:
  minio_data:
  minio_jwt:  # ephemeral volume: JWT written by minio-init, read by prometheus

networks:
  dev:
    driver: bridge
    name: dev-network
  monitoring:
    driver: bridge
    name: monitoring-network
    internal: true

secrets:
  grafana_admin_user:
    file: ../secrets/grafana/grafana_admin_user.txt
  grafana_admin_pwd:
    file: ../secrets/grafana/grafana_admin_pwd.txt
  postgres_db:
    file: ../secrets/postgres/postgres_db.txt
  postgres_user:
    file: ../secrets/postgres/postgres_user.txt
  postgres_pwd:
    file: ../secrets/postgres/postgres_pwd.txt
  minio_admin_user:
    file: ../secrets/minio/minio_admin_user.txt
  minio_admin_pwd:
    file: ../secrets/minio/minio_admin_pwd.txt
