# syntax=docker/dockerfile:1

FROM alpine:3.23.3

RUN apk add --no-cache \
	# pg_dump / pg_restore
    postgresql18-client \
	# required for mc TLS connections
    ca-certificates \
	# to compress
    tzdata \
    # utilitary
    curl

# hand-change version if needed
ENV SUPERCRONIC_VERSION=v0.2.45 \
    SUPERCRONIC_URL=https://github.com/aptible/supercronic/releases/download/v0.2.45/supercronic-linux-amd64 \
    SUPERCRONIC_SHA1SUM=e894b193bea75a5ee644e700c59e30eedc804cf7 \
    SUPERCRONIC_BIN=supercronic-linux-amd64
    # not sure about this one yet, I didn't find any that has been release recently (maybe chainguard has one)
    MC_VERSION=RELEASE.2025-04-03T17-07-56Z


RUN curl -fsSLO "$SUPERCRONIC_URL" \
    && echo "${SUPERCRONIC_SHA1SUM}  ${SUPERCRONIC_BIN}" | sha1sum -c - \
    && chmod +x "$SUPERCRONIC_BIN" \
    && mv "$SUPERCRONIC_BIN" /usr/local/bin/supercronic

# mc: MinIO client for mirror operations
# https://dl.min.io/client/mc/release/linux-amd64/
RUN curl -fsSLo /usr/local/bin/mc \
    "https://dl.min.io/client/mc/release/linux-amd64/archive/mc.${MC_VERSION}" \
    && chmod +x /usr/local/bin/mc

COPY infra/services/backup/backup.sh  /usr/local/bin/backup.sh
COPY infra/services/backup/restore.sh /usr/local/bin/restore.sh
COPY infra/services/backup/crontab    /etc/supercronic/crontab

RUN chmod +x /usr/local/bin/backup.sh /usr/local/bin/restore.sh \
    && mkdir -p /backups/daily /backups/weekly /backups/minio

CMD ["supercronic", "/etc/supercronic/crontab"]
